# gen_casestudy_data.py — extract SKAB valve1_1 series for fig_casestudy.html
# READ-ONLY over the benchmark run dir; emits compact JS arrays + verification stats.
import csv, json, math
from pathlib import Path as _P

_BASE = _P(__file__).resolve().parent
def safe_path(x):
    p = _P(x).resolve(); p.relative_to(_BASE); return p
def safe_open(x, mode="r", **kw):
    return open(safe_path(x), mode, **kw)

RUN = r"D:\codes\myskills\industrial-deep-diagnostic\workspace\diagnostic-runs\202609171630389_bench_skab_valve1_1"
CSV = RUN + r"\00_input\data.csv"

rows = []
with open(CSV, newline="", encoding="utf-8") as f:
    r = csv.DictReader(f)
    for d in r:
        rows.append(d)
n = len(rows)
idx = list(range(1, n + 1))  # 1-based row index
flow = [float(d["Volume Flow RateRMS"]) for d in rows]
curr = [float(d["Current"]) for d in rows]

W0, W1 = 621, 927  # plateau window (1-based, inclusive)
win = flow[W0 - 1 : W1]
out = flow[: W0 - 1] + flow[W1:]

def mean(v): return sum(v) / len(v)

def welch(a, b):
    ma, mb = mean(a), mean(b)
    va = sum((x - ma) ** 2 for x in a) / (len(a) - 1)
    vb = sum((x - mb) ** 2 for x in b) / (len(b) - 1)
    t = (ma - mb) / math.sqrt(va / len(a) + vb / len(b))
    df = (va / len(a) + vb / len(b)) ** 2 / (
        (va / len(a)) ** 2 / (len(a) - 1) + (vb / len(b)) ** 2 / (len(b) - 1))
    from scipy.stats import t as tdist
    p = 2 * tdist.sf(abs(t), df)
    return ma, mb, t, df, p

wa, wb, t, df, p = welch(win, out)
cwin = sorted(curr[W0 - 1 : W1]); cout = sorted(curr[: W0 - 1] + curr[W1:])
med = lambda v: v[len(v) // 2] if len(v) % 2 else 0.5 * (v[len(v)//2 - 1] + v[len(v)//2])

print(f"n_rows={n}  flow min/max={min(flow)}/{max(flow)}  curr min/max={min(curr):.3f}/{max(curr):.3f}")
print(f"window rows {W0}-{W1} ({len(win)} rows): flow mean={mean(win):.3f}  level={sorted(set(win))}")
print(f"outside: flow mean={mean(out):.3f}  level={sorted(set(out))[:5]}")
print(f"Welch window-vs-outside: dLevel={wb-wa:+.2f}%  t={t:.1f} df={df:.0f} p={p:.2e}")
print(f"current: window median={med(cwin):.3f} A, outside median={med(cout):.3f} A, diff={med(cwin)-med(cout):+.3f} A")

def fmt(v, nd):
    s = f"{v:.{nd}f}".rstrip("0").rstrip(".")
    return s if s else "0"

def jsarr(name, vals, nd, per=22):
    parts = [fmt(v, nd) for v in vals]
    lines = []
    for i in range(0, len(parts), per):
        lines.append(",".join(parts[i : i + per]))
    return f"const {name}=[\n" + ",\n".join(lines) + "\n];"

outjs = jsarr("FLOW", flow, 2) + "\n" + jsarr("CURR", curr, 3)
dst = r"D:\codes\myskills\industrial-deep-diagnostic\paper\workbench\casestudy_data.js"
with safe_open("casestudy_data.js", "w", encoding="utf-8") as f:
    f.write("// generated by paper/workbench/gen_casestudy_data.py — READ-ONLY extraction of\n")
    f.write("// " + RUN + "\\00_input\\data.csv  (1145 rows; 1-based row index; window rows 621-927)\n")
    f.write(outjs + "\n")
print("wrote", dst)
